/**
 * @license
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import {
  parse,
  CSSRule,
  CSSStyleRule,
  CSSGroupingRule,
  CSSMediaRule,
  CSSSupportsRule,
  CSSContainerRule,
  CSSLayerBlockRule,
  CSSLayerStatementRule,
  CSSKeyframesRule,
  CSSFontFaceRule,
  CSSPropertyRule,
  CSSImportRule,
  CSSNamespaceRule,
  CSSStartingStyleRule,
  CSSScopeRule,
  CSSPageRule,
} from '../../../src/index.ts';

export interface CoverageRange {
  start: number;
  end: number;
}

export type ReviewReason =
  | 'UNREFERENCED_KEYFRAMES'
  | 'UNREFERENCED_FONT_FACE'
  | 'DYNAMIC_STATE_PSEUDO'
  | 'INTERACTIVE_WITHOUT_BASE'
  | 'ENVIRONMENTAL_MEDIA_QUERY';

export interface ReviewItem {
  header: string;
  reason: ReviewReason;
  description: string;
  rule: CSSRule;
}

export interface CoveragePruneResult {
  prunedCss: string;
  removedRules: string[];
  retainedRules: string[];
  reviewQueue: ReviewItem[];
}

export interface PruneOptions {
  preserveRootCustomProperties?: boolean;
  preserveKeyframes?: boolean;
  preserveFontFaces?: boolean;
  preserveInteractivePseudoClasses?: boolean;
  preserveEnvironmentalMediaQueries?: boolean;
  /** When true, comments out ambiguous triage rules in the CSS with @cssom-review annotations instead of omitting them */
  annotateReviewRules?: boolean;
}

/**
 * Common interactive and dynamic pseudo-classes.
 */
const INTERACTIVE_PSEUDO_REGEX = /:(?:hover|focus|focus-visible|focus-within|active|target|popover-open|visited)\b/i;
const DYNAMIC_STATE_PSEUDO_REGEX = /:(?:checked|disabled|enabled|valid|invalid|required|optional|read-only|read-write|empty|indeterminate|default)\b/i;

/**
 * Strips pseudo-classes to retrieve the base selector for matching against active rules.
 */
function extractBaseSelector(selector: string): string {
  return selector
    .replace(/:(?:focus-visible|focus-within|popover-open|hover|focus|active|target|visited)\b/gi, '')
    .replace(/:(?:checked|disabled|enabled|valid|invalid|required|optional|read-only|read-write|empty|indeterminate|default)\b/gi, '')
    .trim();
}

/**
 * Environmental media queries that should be guaranteed preserved because point-in-time
 * browser capture does not evaluate alternative color schemes or print output.
 */
function isEnvironmentalMedia(conditionText: string): boolean {
  const lower = conditionText.toLowerCase();
  return (
    lower.includes('print') ||
    lower.includes('prefers-color-scheme') ||
    lower.includes('prefers-reduced-motion') ||
    lower.includes('prefers-contrast') ||
    lower.includes('forced-colors') ||
    lower.includes('dynamic-range')
  );
}

/**
 * Determines whether any range intersects with [start, end).
 * If parentSpan is provided, ranges that envelop the entire parent span are ignored
 * so that outer grouping at-rules (@layer, .parent) do not swallow unused children.
 */
function isCovered(
  start: number,
  end: number,
  ranges: CoverageRange[],
  parentSpan?: { start: number; end: number }
): boolean {
  for (const r of ranges) {
    // If an enclosing parent span exists and this coverage range envelops the entire parent,
    // it was generated by CDP for the grouping block, not for this specific child rule.
    if (parentSpan && r.start <= parentSpan.start && r.end >= parentSpan.end) {
      continue;
    }
    if (Math.max(start, r.start) < Math.min(end, r.end)) {
      return true;
    }
  }
  return false;
}

/**
 * Extracts the canonical rule header (selector or at-rule prelude) cleanly.
 */
function getRuleHeader(rule: CSSRule, source: string): string {
  if (rule instanceof CSSStyleRule) {
    return rule.selectorText;
  }
  if (rule instanceof CSSMediaRule) {
    return `@media ${rule.conditionText}`;
  }
  if (rule instanceof CSSSupportsRule) {
    return `@supports ${rule.conditionText}`;
  }
  if (rule instanceof CSSContainerRule) {
    return `@container ${rule.conditionText}`;
  }
  if (rule instanceof CSSLayerBlockRule) {
    return rule.name ? `@layer ${rule.name}` : '@layer';
  }
  if (rule instanceof CSSLayerStatementRule) {
    return `@layer ${rule.nameList.join(', ')}`;
  }
  if (rule instanceof CSSKeyframesRule) {
    return `@keyframes ${rule.name}`;
  }
  if (rule instanceof CSSFontFaceRule) {
    return '@font-face';
  }
  if (rule instanceof CSSPropertyRule) {
    return `@property ${rule.name}`;
  }
  if (rule instanceof CSSStartingStyleRule) {
    return '@starting-style';
  }
  if (rule instanceof CSSScopeRule) {
    const start = rule.start ? `(${rule.start})` : '';
    const end = rule.end ? ` to (${rule.end})` : '';
    const prelude = `${start}${end}`.trim();
    return prelude ? `@scope ${prelude}` : '@scope';
  }
  if (rule instanceof CSSPageRule) {
    return rule.selectorText ? `@page ${rule.selectorText}` : '@page';
  }
  if (rule instanceof CSSImportRule || rule instanceof CSSNamespaceRule) {
    return rule.cssText.replace(/;$/, '').trim();
  }
  const loc = rule.location;
  if (!loc) return '';
  if (loc.bodyStart !== undefined) {
    const braceIdx = source.lastIndexOf('{', loc.bodyStart);
    const headerEnd = braceIdx >= loc.start ? braceIdx : loc.bodyStart;
    return source.slice(loc.start, headerEnd).trim();
  }
  const semiIdx = source.lastIndexOf(';', loc.end);
  const headerEnd = semiIdx >= loc.start ? semiIdx : loc.end;
  return source.slice(loc.start, headerEnd).trim();
}

/**
 * Returns prunable child CSS rules that have source locations.
 */
function getChildRules(rule: CSSRule): CSSRule[] {
  if ('cssRules' in rule && rule.cssRules) {
    const list = (rule as CSSGroupingRule).cssRules;
    const children: CSSRule[] = [];
    for (let i = 0; i < list.length; i++) {
      const item = list[i];
      if (item.location) {
        children.push(item);
      }
    }
    return children;
  }
  return [];
}

/**
 * Checks if a rule is a grouping rule with nested child rules that can be pruned individually.
 */
function isGroupingRule(rule: CSSRule): boolean {
  return rule instanceof CSSGroupingRule && getChildRules(rule).length > 0;
}

/**
 * Recursively walks rules and collects all referenced animation names and font family names
 * declared across all active style rules.
 */
function collectActiveAssetReferences(
  rules: CSSRule[],
  isRetained: (r: CSSRule) => boolean
): { animations: Set<string>; fonts: Set<string> } {
  const animations = new Set<string>();
  const fonts = new Set<string>();

  function walk(rule: CSSRule) {
    if (isRetained(rule)) {
      if (rule instanceof CSSStyleRule) {
        const style = rule.style;
        const animName = style.getPropertyValue('animation-name');
        if (animName) {
          animName.split(',').forEach(s => animations.add(s.trim()));
        }
        const anim = style.getPropertyValue('animation');
        if (anim) {
          anim.split(/\s+/).forEach(token => animations.add(token.trim()));
        }
        const fontFam = style.getPropertyValue('font-family');
        if (fontFam) {
          fontFam.split(',').forEach(s => fonts.add(s.trim().replace(/^['"]|['"]$/g, '')));
        }
        const font = style.getPropertyValue('font');
        if (font) {
          font.split(/\s+/).forEach(s => fonts.add(s.trim().replace(/^['"]|['"]$/g, '')));
        }
      }
    }
    if ('cssRules' in rule && rule.cssRules) {
      const list = (rule as CSSGroupingRule).cssRules;
      for (let i = 0; i < list.length; i++) {
        walk(list[i]);
      }
    }
  }

  for (const r of rules) {
    walk(r);
  }

  return { animations, fonts };
}

/**
 * Coverage-guided CSS dead-code pruner with Human-in-the-Loop Triage and Guaranteed Preserves.
 *
 * Takes raw CSS stylesheet text and coverage ranges produced by Chrome DevTools / Puppeteer
 * and prunes unused rules while maintaining structural ordering, active animations,
 * interactive states, and surfacing ambiguous rules into a review queue.
 */
export function pruneUnusedCss(
  css: string,
  coverageRanges: CoverageRange[],
  options?: PruneOptions
): CoveragePruneResult {
  const preserveRootCustomProperties = options?.preserveRootCustomProperties ?? true;
  const preserveKeyframes = options?.preserveKeyframes ?? true;
  const preserveFontFaces = options?.preserveFontFaces ?? true;
  const preserveInteractive = options?.preserveInteractivePseudoClasses ?? true;
  const preserveEnvironmental = options?.preserveEnvironmentalMediaQueries ?? true;
  const annotateReview = options?.annotateReviewRules ?? false;

  const sheet = parse(css);
  const removedRules: string[] = [];
  const retainedRules: string[] = [];
  const retainedSet = new Set<CSSRule>();
  const reviewQueue: ReviewItem[] = [];
  const annotatedReviewSet = new Set<CSSRule>();

  // Set of base selectors that have confirmed usage across retained rules
  const activeBaseSelectors = new Set<string>();

  // First pass: identify all high-confidence used rules from coverage
  function identifyActiveRules(rule: CSSRule, parentSpan?: { start: number; end: number }) {
    const loc = rule.location;
    if (!loc) return;

    if (rule instanceof CSSStyleRule) {
      if (isCovered(loc.start, loc.end, coverageRanges, parentSpan)) {
        activeBaseSelectors.add(extractBaseSelector(rule.selectorText));
      }
    }

    if (isGroupingRule(rule)) {
      const mySpan = { start: loc.start, end: loc.end };
      for (const child of getChildRules(rule)) {
        identifyActiveRules(child, mySpan);
      }
    }
  }

  for (let i = 0; i < sheet.cssRules.length; i++) {
    identifyActiveRules(sheet.cssRules[i]);
  }

  // Pre-scan for active animation and font references
  const activeAssets = collectActiveAssetReferences(
    Array.from(sheet.cssRules),
    (r) => {
      const loc = r.location;
      if (!loc) return false;
      return isCovered(loc.start, loc.end, coverageRanges);
    }
  );

  // Main rule evaluation pass
  function evaluateRuleUsage(rule: CSSRule, parentSpan?: { start: number; end: number }): boolean {
    const loc = rule.location;
    if (!loc) return false;
    const header = getRuleHeader(rule, css);

    // 1. TIER 2: Guaranteed Preserves - Structural at-rules
    if (
      rule instanceof CSSImportRule ||
      rule instanceof CSSNamespaceRule ||
      rule instanceof CSSLayerStatementRule
    ) {
      retainedRules.push(header);
      retainedSet.add(rule);
      return true;
    }

    // 2. TIER 2: Guaranteed Preserves - Environmental media queries (print, dark mode)
    // Only enabled if preserveEnvironmental is true AND preserveRootCustomProperties is not explicitly disabled
    if (preserveEnvironmental && preserveRootCustomProperties && rule instanceof CSSMediaRule && isEnvironmentalMedia(rule.conditionText)) {
      retainedRules.push(header);
      retainedSet.add(rule);
      // Retain all children inside environmental media queries
      for (const child of getChildRules(rule)) {
        retainedSet.add(child);
        retainedRules.push(getRuleHeader(child, css));
      }
      return true;
    }

    // 3. TIER 2: Guaranteed Preserves - Custom properties & design tokens
    if (preserveRootCustomProperties) {
      if (rule instanceof CSSPropertyRule) {
        retainedRules.push(header);
        retainedSet.add(rule);
        return true;
      }
      if (rule instanceof CSSStyleRule) {
        const sel = rule.selectorText.trim();
        const hasCustomProps = rule.style.declarations.some(d => d.name.startsWith('--'));
        const isRootSelector = sel === ':root' || sel === 'html' || sel === ':host';
        if (hasCustomProps && (isRootSelector || sel.startsWith(':root') || sel.startsWith('html'))) {
          retainedRules.push(header);
          retainedSet.add(rule);
          return true;
        }
      }
    }

    // 4. AST-linked Asset Resolution: @keyframes
    if (rule instanceof CSSKeyframesRule) {
      if (!preserveKeyframes) {
        removedRules.push(header);
        return false;
      }
      const isReferenced = activeAssets.animations.has(rule.name);
      if (isReferenced) {
        retainedRules.push(header);
        retainedSet.add(rule);
        return true;
      }
      // Kept via blanket option, but surface to review queue as ambiguous
      retainedRules.push(header);
      retainedSet.add(rule);
      reviewQueue.push({
        header,
        reason: 'UNREFERENCED_KEYFRAMES',
        description: `@keyframes ${rule.name} was not referenced by any active CSS animation declaration.`,
        rule,
      });
      return true;
    }

    // 5. AST-linked Asset Resolution: @font-face
    if (rule instanceof CSSFontFaceRule) {
      if (!preserveFontFaces) {
        removedRules.push(header);
        return false;
      }
      const fontFam = rule.style.getPropertyValue('font-family').replace(/^['"]|['"]$/g, '').trim();
      const isReferenced = fontFam ? activeAssets.fonts.has(fontFam) : false;
      if (isReferenced) {
        retainedRules.push(header);
        retainedSet.add(rule);
        return true;
      }
      retainedRules.push(header);
      retainedSet.add(rule);
      reviewQueue.push({
        header,
        reason: 'UNREFERENCED_FONT_FACE',
        description: `@font-face '${fontFam || 'unknown'}' was not referenced by any active font-family.`,
        rule,
      });
      return true;
    }

    // 6. Interactive & Dynamic State Pseudo-Classes
    if (rule instanceof CSSStyleRule) {
      const sel = rule.selectorText;
      const isInteractive = INTERACTIVE_PSEUDO_REGEX.test(sel);
      const isDynamicState = DYNAMIC_STATE_PSEUDO_REGEX.test(sel);

      if (isInteractive || isDynamicState) {
        const base = extractBaseSelector(sel);
        const baseActive = base !== '' && activeBaseSelectors.has(base);

        if (preserveInteractive && isInteractive && baseActive) {
          // Guaranteed preserve: base selector is actively in use
          retainedRules.push(header);
          retainedSet.add(rule);
          return true;
        }

        if (isDynamicState && baseActive) {
          // Dynamic state on active base: add to review queue
          reviewQueue.push({
            header,
            reason: 'DYNAMIC_STATE_PSEUDO',
            description: `Dynamic state pseudo-class on active base selector '${base}'.`,
            rule,
          });
          if (annotateReview) {
            annotatedReviewSet.add(rule);
          }
        } else if (isInteractive && !baseActive) {
          // Orphaned pseudo-class: there is no active base element rule!
          reviewQueue.push({
            header,
            reason: 'INTERACTIVE_WITHOUT_BASE',
            description: `Interactive pseudo-class without active base selector '${base || sel}'.`,
            rule,
          });
          if (annotateReview) {
            annotatedReviewSet.add(rule);
          }
        }
      }
    }

    // 7. Grouping rules (@media, @layer, @supports, @container, @scope)
    if (isGroupingRule(rule)) {
      const mySpan = { start: loc.start, end: loc.end };
      const children = getChildRules(rule);
      let anyChildUsed = false;
      for (const child of children) {
        if (evaluateRuleUsage(child, mySpan)) {
          anyChildUsed = true;
        }
      }
      const selfCovered = isCovered(loc.start, loc.bodyStart ?? loc.end, coverageRanges, parentSpan);
      if (anyChildUsed || selfCovered) {
        retainedRules.push(header);
        retainedSet.add(rule);
        return true;
      }
      removedRules.push(header);
      return false;
    }

    // 8. Normal style rules: checked against coverage with parent span exclusion
    const used = isCovered(loc.start, loc.end, coverageRanges, parentSpan);
    if (used) {
      retainedRules.push(header);
      retainedSet.add(rule);
      return true;
    } else {
      if (!annotatedReviewSet.has(rule)) {
        removedRules.push(header);
      }
      return false;
    }
  }

  // Evaluate all top-level rules
  for (let i = 0; i < sheet.cssRules.length; i++) {
    evaluateRuleUsage(sheet.cssRules[i]);
  }

  // Recursive slice/splicing to preserve comments and layout accurately
  function serializeKeptSlice(rule: CSSRule): string {
    const loc = rule.location!;
    const children = isGroupingRule(rule) ? getChildRules(rule) : [];

    // If not a grouping rule with children, return verbatim original text
    if (children.length === 0 || loc.bodyStart === undefined || loc.bodyEnd === undefined) {
      if (annotatedReviewSet.has(rule)) {
        const ruleText = css.slice(loc.start, loc.end);
        const item = reviewQueue.find(q => q.rule === rule);
        return `/* @cssom-review: ${item?.reason || 'AMBIGUOUS'} (${item?.description || ''})\n${ruleText}\n*/`;
      }
      return css.slice(loc.start, loc.end);
    }

    // Grouping rule: preserve header up to bodyStart ('{')
    const headerPrefix = css.slice(loc.start, loc.bodyStart);
    const closingSuffix = css.slice(loc.bodyEnd, loc.end);

    let innerContent = '';
    let lastPos = loc.bodyStart;

    for (const child of children) {
      const childLoc = child.location!;
      // FIX DATA LOSS BUG: Always flush text between lastPos and childLoc.start
      // so property declarations between nested rules are preserved!
      innerContent += css.slice(lastPos, childLoc.start);

      if (retainedSet.has(child)) {
        innerContent += serializeKeptSlice(child);
      } else if (annotatedReviewSet.has(child)) {
        const childText = css.slice(childLoc.start, childLoc.end);
        const item = reviewQueue.find(q => q.rule === child);
        innerContent += `/* @cssom-review: ${item?.reason || 'AMBIGUOUS'}\n${childText}\n*/`;
      }
      lastPos = childLoc.end;
    }

    // Retain trailing whitespace/comments between last child and closing brace
    innerContent += css.slice(lastPos, loc.bodyEnd);

    return `${headerPrefix}${innerContent}${closingSuffix}`;
  }

  // Build top-level pruned text
  let prunedCss = '';
  let lastPos = 0;

  for (let i = 0; i < sheet.cssRules.length; i++) {
    const rootRule = sheet.cssRules[i];
    const loc = rootRule.location;
    if (!loc) continue;

    if (retainedSet.has(rootRule)) {
      prunedCss += css.slice(lastPos, loc.start);
      prunedCss += serializeKeptSlice(rootRule);
      lastPos = loc.end;
    } else if (annotatedReviewSet.has(rootRule)) {
      prunedCss += css.slice(lastPos, loc.start);
      const ruleText = css.slice(loc.start, loc.end);
      const item = reviewQueue.find(q => q.rule === rootRule);
      prunedCss += `/* @cssom-review: ${item?.reason || 'AMBIGUOUS'} (${item?.description || ''})\n${ruleText}\n*/`;
      lastPos = loc.end;
    } else {
      lastPos = loc.end;
    }
  }

  // Append remaining text (trailing comments/whitespace)
  prunedCss += css.slice(lastPos);

  // Clean up excess blank lines (>2 newlines) while preserving formatting
  const cleanedCss = prunedCss.replace(/\n{3,}/g, '\n\n').trim();

  return {
    prunedCss: cleanedCss,
    removedRules,
    retainedRules,
    reviewQueue,
  };
}
