/**
 * @license
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// @generated by scripts/codegen/generate_units_code.ts. Do not edit.
// Machine-generated.

import { CSSUnitValue } from '../typed-om.ts';
import type { CSSUnit } from './units.ts';

export const CSSFactories = {
  cap: (v: number) => new CSSUnitValue(v, 'cap' as CSSUnit),
  ch: (v: number) => new CSSUnitValue(v, 'ch' as CSSUnit),
  cm: (v: number) => new CSSUnitValue(v, 'cm' as CSSUnit),
  cqb: (v: number) => new CSSUnitValue(v, 'cqb' as CSSUnit),
  cqh: (v: number) => new CSSUnitValue(v, 'cqh' as CSSUnit),
  cqi: (v: number) => new CSSUnitValue(v, 'cqi' as CSSUnit),
  cqmax: (v: number) => new CSSUnitValue(v, 'cqmax' as CSSUnit),
  cqmin: (v: number) => new CSSUnitValue(v, 'cqmin' as CSSUnit),
  cqw: (v: number) => new CSSUnitValue(v, 'cqw' as CSSUnit),
  deg: (v: number) => new CSSUnitValue(v, 'deg' as CSSUnit),
  dpcm: (v: number) => new CSSUnitValue(v, 'dpcm' as CSSUnit),
  dpi: (v: number) => new CSSUnitValue(v, 'dpi' as CSSUnit),
  dppx: (v: number) => new CSSUnitValue(v, 'dppx' as CSSUnit),
  dvb: (v: number) => new CSSUnitValue(v, 'dvb' as CSSUnit),
  dvh: (v: number) => new CSSUnitValue(v, 'dvh' as CSSUnit),
  dvi: (v: number) => new CSSUnitValue(v, 'dvi' as CSSUnit),
  dvmax: (v: number) => new CSSUnitValue(v, 'dvmax' as CSSUnit),
  dvmin: (v: number) => new CSSUnitValue(v, 'dvmin' as CSSUnit),
  dvw: (v: number) => new CSSUnitValue(v, 'dvw' as CSSUnit),
  em: (v: number) => new CSSUnitValue(v, 'em' as CSSUnit),
  ex: (v: number) => new CSSUnitValue(v, 'ex' as CSSUnit),
  fr: (v: number) => new CSSUnitValue(v, 'fr' as CSSUnit),
  grad: (v: number) => new CSSUnitValue(v, 'grad' as CSSUnit),
  Hz: (v: number) => new CSSUnitValue(v, 'hz' as CSSUnit),
  ic: (v: number) => new CSSUnitValue(v, 'ic' as CSSUnit),
  in: (v: number) => new CSSUnitValue(v, 'in' as CSSUnit),
  kHz: (v: number) => new CSSUnitValue(v, 'khz' as CSSUnit),
  lh: (v: number) => new CSSUnitValue(v, 'lh' as CSSUnit),
  lvb: (v: number) => new CSSUnitValue(v, 'lvb' as CSSUnit),
  lvh: (v: number) => new CSSUnitValue(v, 'lvh' as CSSUnit),
  lvi: (v: number) => new CSSUnitValue(v, 'lvi' as CSSUnit),
  lvmax: (v: number) => new CSSUnitValue(v, 'lvmax' as CSSUnit),
  lvmin: (v: number) => new CSSUnitValue(v, 'lvmin' as CSSUnit),
  lvw: (v: number) => new CSSUnitValue(v, 'lvw' as CSSUnit),
  mm: (v: number) => new CSSUnitValue(v, 'mm' as CSSUnit),
  ms: (v: number) => new CSSUnitValue(v, 'ms' as CSSUnit),
  number: (v: number) => new CSSUnitValue(v, 'number' as CSSUnit),
  pc: (v: number) => new CSSUnitValue(v, 'pc' as CSSUnit),
  percent: (v: number) => new CSSUnitValue(v, 'percent' as CSSUnit),
  pt: (v: number) => new CSSUnitValue(v, 'pt' as CSSUnit),
  px: (v: number) => new CSSUnitValue(v, 'px' as CSSUnit),
  Q: (v: number) => new CSSUnitValue(v, 'q' as CSSUnit),
  rad: (v: number) => new CSSUnitValue(v, 'rad' as CSSUnit),
  rcap: (v: number) => new CSSUnitValue(v, 'rcap' as CSSUnit),
  rch: (v: number) => new CSSUnitValue(v, 'rch' as CSSUnit),
  rem: (v: number) => new CSSUnitValue(v, 'rem' as CSSUnit),
  rex: (v: number) => new CSSUnitValue(v, 'rex' as CSSUnit),
  ric: (v: number) => new CSSUnitValue(v, 'ric' as CSSUnit),
  rlh: (v: number) => new CSSUnitValue(v, 'rlh' as CSSUnit),
  s: (v: number) => new CSSUnitValue(v, 's' as CSSUnit),
  svb: (v: number) => new CSSUnitValue(v, 'svb' as CSSUnit),
  svh: (v: number) => new CSSUnitValue(v, 'svh' as CSSUnit),
  svi: (v: number) => new CSSUnitValue(v, 'svi' as CSSUnit),
  svmax: (v: number) => new CSSUnitValue(v, 'svmax' as CSSUnit),
  svmin: (v: number) => new CSSUnitValue(v, 'svmin' as CSSUnit),
  svw: (v: number) => new CSSUnitValue(v, 'svw' as CSSUnit),
  turn: (v: number) => new CSSUnitValue(v, 'turn' as CSSUnit),
  vb: (v: number) => new CSSUnitValue(v, 'vb' as CSSUnit),
  vh: (v: number) => new CSSUnitValue(v, 'vh' as CSSUnit),
  vi: (v: number) => new CSSUnitValue(v, 'vi' as CSSUnit),
  vmax: (v: number) => new CSSUnitValue(v, 'vmax' as CSSUnit),
  vmin: (v: number) => new CSSUnitValue(v, 'vmin' as CSSUnit),
  vw: (v: number) => new CSSUnitValue(v, 'vw' as CSSUnit),
  x: (v: number) => new CSSUnitValue(v, 'x' as CSSUnit),
};
