/**
 * @license
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// @generated by scripts/codegen/generate_logical_mappings.ts. Do not edit.
// Machine-generated.

/**
 * Logical property to physical property mapping for default horizontal-tb, ltr.
 * @see https://drafts.csswg.org/css-logical-1/#box
 */
export const LOGICAL_MAPPING = {
  'background-position-block': 'background-position-y',
  'background-position-inline': 'background-position-x',
  'background-repeat-block': 'background-repeat-y',
  'background-repeat-inline': 'background-repeat-x',
  'block-size': 'height',
  'border-block-end-clip': 'border-bottom-clip',
  'border-block-end-color': 'border-bottom-color',
  'border-block-end-style': 'border-bottom-style',
  'border-block-end-width': 'border-bottom-width',
  'border-block-start-clip': 'border-top-clip',
  'border-block-start-color': 'border-top-color',
  'border-block-start-style': 'border-top-style',
  'border-block-start-width': 'border-top-width',
  'border-end-end-radius': 'border-bottom-right-radius',
  'border-end-start-radius': 'border-bottom-left-radius',
  'border-inline-end-clip': 'border-right-clip',
  'border-inline-end-color': 'border-right-color',
  'border-inline-end-style': 'border-right-style',
  'border-inline-end-width': 'border-right-width',
  'border-inline-start-clip': 'border-left-clip',
  'border-inline-start-color': 'border-left-color',
  'border-inline-start-style': 'border-left-style',
  'border-inline-start-width': 'border-left-width',
  'border-start-end-radius': 'border-top-right-radius',
  'border-start-start-radius': 'border-top-left-radius',
  'contain-intrinsic-block-size': 'contain-intrinsic-height',
  'contain-intrinsic-inline-size': 'contain-intrinsic-width',
  'corner-end-end-shape': 'corner-bottom-right-shape',
  'corner-end-start-shape': 'corner-bottom-left-shape',
  'corner-start-end-shape': 'corner-top-right-shape',
  'corner-start-start-shape': 'corner-top-left-shape',
  'inline-size': 'width',
  'inset-block-end': 'bottom',
  'inset-block-start': 'top',
  'inset-inline-end': 'right',
  'inset-inline-start': 'left',
  'margin-block-end': 'margin-bottom',
  'margin-block-start': 'margin-top',
  'margin-inline-end': 'margin-right',
  'margin-inline-start': 'margin-left',
  'max-block-size': 'max-height',
  'max-inline-size': 'max-width',
  'min-block-size': 'min-height',
  'min-inline-size': 'min-width',
  'overflow-block': 'overflow-y',
  'overflow-clip-margin-block-end': 'overflow-clip-margin-bottom',
  'overflow-clip-margin-block-start': 'overflow-clip-margin-top',
  'overflow-clip-margin-inline-end': 'overflow-clip-margin-right',
  'overflow-clip-margin-inline-start': 'overflow-clip-margin-left',
  'overflow-inline': 'overflow-x',
  'overscroll-behavior-block': 'overscroll-behavior-y',
  'overscroll-behavior-inline': 'overscroll-behavior-x',
  'padding-block-end': 'padding-bottom',
  'padding-block-start': 'padding-top',
  'padding-inline-end': 'padding-right',
  'padding-inline-start': 'padding-left',
  'scroll-margin-block-end': 'scroll-margin-bottom',
  'scroll-margin-block-start': 'scroll-margin-top',
  'scroll-margin-inline-end': 'scroll-margin-right',
  'scroll-margin-inline-start': 'scroll-margin-left',
  'scroll-padding-block-end': 'scroll-padding-bottom',
  'scroll-padding-block-start': 'scroll-padding-top',
  'scroll-padding-inline-end': 'scroll-padding-right',
  'scroll-padding-inline-start': 'scroll-padding-left',
} as const;

// Physical to Logical (reverse mapping)
export const PHYSICAL_TO_LOGICAL: Record<string, string[]> = {};
for (const [logical, physical] of Object.entries(LOGICAL_MAPPING)) {
  if (!PHYSICAL_TO_LOGICAL[physical as string]) PHYSICAL_TO_LOGICAL[physical as string] = [];
  PHYSICAL_TO_LOGICAL[physical as string].push(logical);
}

/**
 * Resolves a logical property to its physical counterpart based on writing mode and direction.
 */
export function resolveLogicalProperty(name: string, writingMode: string = 'horizontal-tb', direction: string = 'ltr'): string {
  if (!(name in LOGICAL_MAPPING)) {
    return name;
  }

  let blockStart = 'top';
  let blockEnd = 'bottom';
  let inlineStart = 'left';
  let inlineEnd = 'right';
  let blockAxis = 'y';
  let inlineAxis = 'x';

  if (writingMode === 'vertical-rl') {
    blockStart = 'right';
    blockEnd = 'left';
    inlineStart = 'top';
    inlineEnd = 'bottom';
    blockAxis = 'x';
    inlineAxis = 'y';
  } else if (writingMode === 'vertical-lr') {
    blockStart = 'left';
    blockEnd = 'right';
    inlineStart = 'top';
    inlineEnd = 'bottom';
    blockAxis = 'x';
    inlineAxis = 'y';
  }

  if (direction === 'rtl') {
    const tmp = inlineStart;
    inlineStart = inlineEnd;
    inlineEnd = tmp;
  }

  if (name.startsWith('inset-block-start')) return blockStart;
  if (name.startsWith('inset-block-end')) return blockEnd;
  if (name.startsWith('inset-inline-start')) return inlineStart;
  if (name.startsWith('inset-inline-end')) return inlineEnd;

    const radius = (s1: string, s2: string) => {
      const v = (s1 === 'top' || s1 === 'bottom') ? s1 : s2;
      const h = (s1 === 'left' || s1 === 'right') ? s1 : s2;
      return `-${v}-${h}-radius`;
    };
    const shape = (s1: string, s2: string) => {
      const v = (s1 === 'top' || s1 === 'bottom') ? s1 : s2;
      const h = (s1 === 'left' || s1 === 'right') ? s1 : s2;
      return `-${v}-${h}-shape`;
    };

    const replacements = [
      { logical: '-block-start', physical: `-${blockStart}` },
      { logical: '-block-end', physical: `-${blockEnd}` },
      { logical: '-inline-start', physical: `-${inlineStart}` },
      { logical: '-inline-end', physical: `-${inlineEnd}` },
      { logical: '-start-start-radius', physical: radius(blockStart, inlineStart) },
      { logical: '-start-end-radius', physical: radius(blockStart, inlineEnd) },
      { logical: '-end-start-radius', physical: radius(blockEnd, inlineStart) },
      { logical: '-end-end-radius', physical: radius(blockEnd, inlineEnd) },
      { logical: '-start-start-shape', physical: shape(blockStart, inlineStart) },
      { logical: '-start-end-shape', physical: shape(blockStart, inlineEnd) },
      { logical: '-end-start-shape', physical: shape(blockEnd, inlineStart) },
      { logical: '-end-end-shape', physical: shape(blockEnd, inlineEnd) },
      { logical: '-block', physical: `-${blockAxis}` },
      { logical: '-inline', physical: `-${inlineAxis}` },
    ];

  let resolved = name;
  for (const { logical, physical } of replacements) {
    if (resolved.includes(logical)) {
      resolved = resolved.replace(logical, physical);
      break;
    }
  }

  if (resolved === 'block-size') return writingMode.startsWith('vertical') ? 'width' : 'height';
  if (resolved === 'inline-size') return writingMode.startsWith('vertical') ? 'height' : 'width';
  if (resolved === 'min-block-size') return writingMode.startsWith('vertical') ? 'min-width' : 'min-height';
  if (resolved === 'min-inline-size') return writingMode.startsWith('vertical') ? 'min-height' : 'min-width';
  if (resolved === 'max-block-size') return writingMode.startsWith('vertical') ? 'max-width' : 'max-height';
  if (resolved === 'max-inline-size') return writingMode.startsWith('vertical') ? 'max-height' : 'max-width';
  if (resolved === 'contain-intrinsic-block-size') return writingMode.startsWith('vertical') ? 'contain-intrinsic-width' : 'contain-intrinsic-height';
  if (resolved === 'contain-intrinsic-inline-size') return writingMode.startsWith('vertical') ? 'contain-intrinsic-height' : 'contain-intrinsic-width';

  return resolved;
}

export function resolvePhysicalProperty(name: string, writingMode: string = 'horizontal-tb', direction: string = 'ltr'): string {
  for (const logical in LOGICAL_MAPPING) {
    const resolved = resolveLogicalProperty(logical, writingMode, direction);
    if (resolved === name) {
      return logical;
    }
  }
  return name;
}

export function getPhysicalToLogicalMapping(physicals: readonly string[], writingMode: string = 'horizontal-tb', direction: string = 'ltr'): Record<string, string> {
  const mapping: Record<string, string> = {};
  for (const ph of physicals) {
    mapping[ph] = resolvePhysicalProperty(ph, writingMode, direction);
  }
  return mapping;
}
