/** @license Copyright 2026 Google LLC. SPDX-License-Identifier: Apache-2.0 */
// @generated by scripts/codegen/generate_math_functions.ts. Do not edit.
// Machine-generated.

export const MATH_FUNCTIONS = [
  'abs',
  'acos',
  'asin',
  'atan',
  'atan2',
  'cos',
  'exp',
  'hypot',
  'log',
  'mod',
  'pow',
  'rem',
  'sign',
  'sin',
  'sqrt',
  'tan',
];
