/** @license Copyright 2026 Google LLC. SPDX-License-Identifier: Apache-2.0 */
import fs from 'node:fs';

const MDN_SELECTORS_PATH = 'node_modules/mdn-data/css/selectors.json';
const OUTPUT_PATH = 'src/data/selectors.ts';

function main() {
    const selectors = JSON.parse(fs.readFileSync(MDN_SELECTORS_PATH, 'utf8'));
    
    const pseudoClasses = new Set<string>();
    const pseudoElements = new Set<string>();

    for (const [name] of Object.entries(selectors)) {
        if (name.startsWith('::')) {
            pseudoElements.add(name.substring(2).replace('()', '').toLowerCase());
        } else if (name.startsWith(':')) {
            pseudoClasses.add(name.substring(1).replace('()', '').toLowerCase());
        }
    }

    let tsContent = `// @generated by scripts/codegen/generate_selectors.ts. Do not edit.\n// Machine-generated.\n\n`;
    
    tsContent += `export const PSEUDO_CLASSES = new Set([\n`;
    for (const s of Array.from(pseudoClasses).sort()) {
        tsContent += `  '${s}',\n`;
    }
    tsContent += `] as const);\n\n`;

    tsContent += `export const PSEUDO_ELEMENTS = new Set([\n`;
    for (const s of Array.from(pseudoElements).sort()) {
        tsContent += `  '${s}',\n`;
    }
    tsContent += `] as const);\n`;


    fs.writeFileSync(OUTPUT_PATH, tsContent);
    console.log(`Generated ${OUTPUT_PATH}`);
}

main();
