/**
 * @license
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import fs from 'node:fs';

const MDN_SELECTORS_PATH = 'node_modules/mdn-data/css/selectors.json';
const OUTPUT_PATH = 'src/data/gen/selectors.ts';

function main() {
    const selectors = JSON.parse(fs.readFileSync(MDN_SELECTORS_PATH, 'utf8'));
    
    const pseudoClasses = new Set<string>();
    const pseudoElements = new Set<string>();

    for (const [name] of Object.entries(selectors)) {
        if (name.startsWith('::')) {
            pseudoElements.add(name.substring(2).replace('()', '').toLowerCase());
        } else if (name.startsWith(':')) {
            pseudoClasses.add(name.substring(1).replace('()', '').toLowerCase());
        }
    }
    pseudoClasses.add('heading');

    let tsContent = `/**
 * @license
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */\n\n// @generated by scripts/codegen/generate_selectors.ts. Do not edit.\n// Machine-generated.\n\n`;
    
    tsContent += `export const PSEUDO_CLASSES: Set<string> = new Set([\n`;
    for (const s of Array.from(pseudoClasses).sort()) {
        tsContent += `  '${s}',\n`;
    }
    tsContent += `]);\n\n`;

    tsContent += `export const PSEUDO_ELEMENTS: Set<string> = new Set([\n`;
    for (const s of Array.from(pseudoElements).sort()) {
        tsContent += `  '${s}',\n`;
    }
    tsContent += `]);\n`;


    fs.writeFileSync(OUTPUT_PATH, tsContent);
    console.log(`Generated ${OUTPUT_PATH}`);
}

main();
