/** @license Copyright 2026 Google LLC. SPDX-License-Identifier: Apache-2.0 */
import fs from 'node:fs';

const WEBREF_CSS_PATH = 'node_modules/@webref/css/css.json';
const OUTPUT_PATH = 'src/data/media-features.ts';

function main() {
    const css = JSON.parse(fs.readFileSync(WEBREF_CSS_PATH, 'utf8'));
    const mediaAtRule = css.atrules.find((a: { name: string, descriptors: unknown[] }) => a.name === '@media');
    if (!mediaAtRule) {
        console.error('Could not find @media at-rule in @webref/css');
        process.exit(1);
    }

    const features = mediaAtRule.descriptors;
    
    const knownFeatures = new Set<string>();
    const rangeFeatures = new Set<string>();
    const featureValueTypes: Record<string, string[]> = {};
    const featureAllowedIdents: Record<string, string[]> = {};


    for (const f of features) {
        knownFeatures.add(f.name);
        if (f.type === 'range') {
            rangeFeatures.add(f.name);
            knownFeatures.add(`min-${f.name}`);
            knownFeatures.add(`max-${f.name}`);

        }

        const syntax = f.syntax || '';
        const types: string[] = [];
        if (syntax.includes('<length>')) types.push('length');
        if (syntax.includes('<ratio>')) types.push('ratio');
        if (syntax.includes('<integer>')) types.push('integer');
        if (syntax.includes('<resolution>')) types.push('resolution');
        if (syntax.includes('<mq-boolean>')) types.push('integer'); // <mq-boolean> is 0 or 1
        
        const idents = syntax.split('|').map((s: string) => s.trim()).filter((s: string) => !s.startsWith('<') && s !== 'infinite');
        if (idents.length > 0) {
            types.push('ident');
            featureAllowedIdents[f.name] = idents;
        }

        if (types.length > 0) {
            featureValueTypes[f.name] = types;
            if (f.type === 'range') {
                featureValueTypes[`min-${f.name}`] = types;
                featureValueTypes[`max-${f.name}`] = types;
            }
        }
    }

    let tsContent = `// @generated by scripts/codegen/generate_media_features.ts. Do not edit.\n// Machine-generated.\n\n`;
    
    tsContent += `export const KNOWN_FEATURES = new Set([\n`;
    for (const f of Array.from(knownFeatures).sort()) {
        tsContent += `  '${f}',\n`;
    }
    tsContent += `] as const);\n\n`;

    tsContent += `export const RANGE_FEATURES = new Set([\n`;
    for (const f of Array.from(rangeFeatures).sort()) {
        tsContent += `  '${f}',\n`;
    }
    tsContent += `] as const);\n\n`;

    tsContent += `export const FEATURE_VALUE_TYPES: Record<string, readonly string[]> = {\n`;
    for (const [f, types] of Object.entries(featureValueTypes).sort()) {
        tsContent += `  '${f}': ${JSON.stringify(types)} as const,\n`;
    }
    tsContent += `} as const;\n\n`;

    tsContent += `export const FEATURE_ALLOWED_IDENTS: Record<string, readonly string[]> = {\n`;
    for (const [f, idents] of Object.entries(featureAllowedIdents).sort()) {
        tsContent += `  '${f}': ${JSON.stringify(idents)} as const,\n`;
    }
    tsContent += `} as const;\n\n`;




    fs.writeFileSync(OUTPUT_PATH, tsContent);
    console.log(`Generated ${OUTPUT_PATH}`);
}

main();

