/** @license Copyright 2026 Google LLC. SPDX-License-Identifier: Apache-2.0 */
import fs from 'node:fs';

const WEBREF_CSS_PATH = 'node_modules/@webref/css/css.json';
const SHORTHANDS_DATA_TS_PATH = 'src/data/shorthands.ts';

function main() {
    const css = JSON.parse(fs.readFileSync(WEBREF_CSS_PATH, 'utf8'));
    const allShorthands: Record<string, string[]> = {};


    for (const p of css.properties) {
        if (p.longhands) {
            allShorthands[p.name] = p.longhands;
        }
    }

    let data = `// @generated by scripts/codegen/generate_shorthands.ts. Do not edit.\n// Machine-generated shorthand data.\n\n`;
    data += `export const SHORTHANDS_DATA = {\n`;
    for (const name of Object.keys(allShorthands).sort()) {
        data += `  '${name}': ${JSON.stringify(allShorthands[name])},\n`;
    }
    data += `} as const;\n`;

    fs.writeFileSync(SHORTHANDS_DATA_TS_PATH, data);
    console.log(`Generated ${SHORTHANDS_DATA_TS_PATH} with ${Object.keys(allShorthands).length} shorthands.`);
}

main();
