/**
 * @license
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import fs from 'node:fs';

const WEBREF_CSS_PATH = 'node_modules/@webref/css/css.json';
const OUTPUT_PATH = 'src/data/gen/math-functions.ts';

function main() {
    const css = JSON.parse(fs.readFileSync(WEBREF_CSS_PATH, 'utf8'));
    
    // Standard list from specs
    const standardMath = [
        'sin', 'cos', 'tan', 'asin', 'acos', 'atan', 'atan2',
        'pow', 'sqrt', 'exp', 'log', 'hypot',
        'abs', 'sign',
        'mod', 'rem'
    ];

    // We'll look for functions from css-values spec and filter by standard math list
    const mathFunctions = css.functions
        .filter((f: { href: string }) => f.href && (f.href.includes('css-values-4') || f.href.includes('css-values-5')))
        .map((f: { name: string }) => f.name.replace('()', '').toLowerCase())
        .filter((name: string) => standardMath.includes(name));

    const allMath = Array.from(new Set([...mathFunctions, ...standardMath])).sort();

    let tsContent = `/**
 * @license
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */\n\n// @generated by scripts/codegen/generate_math_functions.ts. Do not edit.\n// Machine-generated.\n\n`;
    tsContent += `export const MATH_FUNCTIONS = [\n`;
    for (const f of allMath) {
        tsContent += `  '${f}',\n`;
    }
    tsContent += `];\n`;

    fs.writeFileSync(OUTPUT_PATH, tsContent);
    console.log(`Generated ${OUTPUT_PATH}`);
}

main();
