/**
 * @license
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import fs from 'node:fs';

const WEBREF_CSS_PATH = 'node_modules/@webref/css/css.json';
const OUTPUT_PROPERTIES_PATH = 'src/data/properties.ts';
const OUTPUT_LIST_PATH = 'src/data/property-list.ts';

function toCamelCase(str: string): string {
    return str.replace(/-([a-z])/g, (g) => g[1].toUpperCase());
}

function main() {
    const css = JSON.parse(fs.readFileSync(WEBREF_CSS_PATH, 'utf8'));
    const properties = css.properties.map((p: { name: string }) => p.name);
    
    // Sort and remove duplicates
    const uniqueProperties = Array.from(new Set(properties)).sort() as string[];

    // Generate property-list.ts
    let listContent = `// @generated by scripts/codegen/generate_properties.ts. Do not edit.\n// Machine-generated.\n\n`;
    listContent += `export const SUPPORTED_PROPERTIES = new Set<string>([\n`;
    for (const prop of uniqueProperties) {
        listContent += `  '${prop}',\n`;
    }
    listContent += `]);\n`;
    fs.writeFileSync(OUTPUT_LIST_PATH, listContent);
    console.log(`Generated ${OUTPUT_LIST_PATH} with ${uniqueProperties.length} properties.`);

    // Generate properties.ts
    let tsContent = `// @generated by scripts/codegen/generate_properties.ts. Do not edit.\n// Machine-generated.\n\n`;
    tsContent += `export class CSSStyleProperties {\n`;
    tsContent += `  declare cssFloat: string;\n`;
    for (const prop of uniqueProperties) {
        if (prop.startsWith('--')) continue;
        
        let camelName = toCamelCase(prop);
        if (prop.startsWith('-')) {
            camelName = toCamelCase(prop.substring(1));
            camelName = camelName[0].toLowerCase() + camelName.substring(1);
        }
        
        tsContent += `  declare ${camelName}: string;\n`;
    }
    
    tsContent += `}\n`;

    fs.writeFileSync(OUTPUT_PROPERTIES_PATH, tsContent);
    console.log(`Generated ${OUTPUT_PROPERTIES_PATH} with ${uniqueProperties.length} properties.`);
}

main();
