/**
 * @license
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import fs from 'node:fs';

const WEBREF_CSS_PATH = 'node_modules/@webref/css/css.json';
const LOGICAL_MAPPING_TS_PATH = 'src/data/LogicalMapping.ts';

function main() {
    const css = JSON.parse(fs.readFileSync(WEBREF_CSS_PATH, 'utf8'));

    // Build Logical Mapping using logicalPropertyGroup
    const groups: Record<string, string[]> = {};
    css.properties.forEach((p: { name: string, logicalPropertyGroup?: string }) => {
        if (p.logicalPropertyGroup) {
            if (!groups[p.logicalPropertyGroup]) groups[p.logicalPropertyGroup] = [];
            groups[p.logicalPropertyGroup].push(p.name);
        }
    });

    const mappings: Record<string, string> = {};
    const replacements = [
        { logical: '-block-start', physical: '-top' },
        { logical: '-block-end', physical: '-bottom' },
        { logical: '-inline-start', physical: '-left' },
        { logical: '-inline-end', physical: '-right' },
        { logical: '-start-start-', physical: '-top-left-' },
        { logical: '-start-end-', physical: '-top-right-' },
        { logical: '-end-start-', physical: '-bottom-left-' },
        { logical: '-end-end-', physical: '-bottom-right-' },
        { logical: '-block', physical: '-y' },
        { logical: '-inline', physical: '-x' },
    ];

    for (const group of Object.values(groups)) {
        for (const prop of group) {
            for (const { logical, physical } of replacements) {
                if (prop.includes(logical)) {
                    let candidate = prop.replace(logical, physical);
                    if (group.includes(candidate)) {
                        mappings[prop] = candidate;
                        break;
                    }
                }
            }
        }
        
        // special cases
        for (const prop of group) {
            if (mappings[prop]) continue;
            let candidate = prop.replace('block-size', 'height').replace('inline-size', 'width');
            if (group.includes(candidate) && candidate !== prop) { mappings[prop] = candidate; continue; }
            candidate = prop.replace('inset-block-start', 'top')
                           .replace('inset-block-end', 'bottom')
                           .replace('inset-inline-start', 'left')
                           .replace('inset-inline-end', 'right');
            if (group.includes(candidate) && candidate !== prop) { mappings[prop] = candidate; continue; }
        }
    }

    let tsContent = `// @generated by scripts/codegen/generate_logical_mappings.ts. Do not edit.\n// Machine-generated.\n\n`;
    tsContent += `/**\n * Logical property to physical property mapping for default horizontal-tb, ltr.\n * @see https://drafts.csswg.org/css-logical-1/#box\n */\n`;
    tsContent += `export const LOGICAL_MAPPING = {\n`;
    for (const [logical, physical] of Object.entries(mappings).sort()) {
        tsContent += `  '${logical}': '${physical}',\n`;
    }
    tsContent += `} as const;\n\n`;
    tsContent += `// Physical to Logical (reverse mapping)\n`;
    tsContent += `export const PHYSICAL_TO_LOGICAL: Record<string, string[]> = {};\n`;
    tsContent += `for (const [logical, physical] of Object.entries(LOGICAL_MAPPING)) {\n`;
    tsContent += `  if (!PHYSICAL_TO_LOGICAL[physical as string]) PHYSICAL_TO_LOGICAL[physical as string] = [];\n`;
    tsContent += `  PHYSICAL_TO_LOGICAL[physical as string].push(logical);\n`;
    tsContent += `}\n`;

    tsContent += `\n`;
    tsContent += `/**\n`;
    tsContent += ` * Resolves a logical property to its physical counterpart based on writing mode and direction.\n`;
    tsContent += ` */\n`;
    tsContent += `export function resolveLogicalProperty(name: string, writingMode: string = 'horizontal-tb', direction: string = 'ltr'): string {\n`;
    tsContent += `  if (!(name in LOGICAL_MAPPING)) {\n`;
    tsContent += `    return name;\n`;
    tsContent += `  }\n`;
    tsContent += `\n`;
    tsContent += `  let blockStart = 'top';\n`;
    tsContent += `  let blockEnd = 'bottom';\n`;
    tsContent += `  let inlineStart = 'left';\n`;
    tsContent += `  let inlineEnd = 'right';\n`;
    tsContent += `  let blockAxis = 'y';\n`;
    tsContent += `  let inlineAxis = 'x';\n`;
    tsContent += `\n`;
    tsContent += `  if (writingMode === 'vertical-rl') {\n`;
    tsContent += `    blockStart = 'right';\n`;
    tsContent += `    blockEnd = 'left';\n`;
    tsContent += `    inlineStart = 'top';\n`;
    tsContent += `    inlineEnd = 'bottom';\n`;
    tsContent += `    blockAxis = 'x';\n`;
    tsContent += `    inlineAxis = 'y';\n`;
    tsContent += `  } else if (writingMode === 'vertical-lr') {\n`;
    tsContent += `    blockStart = 'left';\n`;
    tsContent += `    blockEnd = 'right';\n`;
    tsContent += `    inlineStart = 'top';\n`;
    tsContent += `    inlineEnd = 'bottom';\n`;
    tsContent += `    blockAxis = 'x';\n`;
    tsContent += `    inlineAxis = 'y';\n`;
    tsContent += `  }\n`;
    tsContent += `\n`;
    tsContent += `  if (direction === 'rtl') {\n`;
    tsContent += `    const tmp = inlineStart;\n`;
    tsContent += `    inlineStart = inlineEnd;\n`;
    tsContent += `    inlineEnd = tmp;\n`;
    tsContent += `  }\n`;
    tsContent += `\n`;
    tsContent += `  if (name.startsWith('inset-block-start')) return blockStart;\n`;
    tsContent += `  if (name.startsWith('inset-block-end')) return blockEnd;\n`;
    tsContent += `  if (name.startsWith('inset-inline-start')) return inlineStart;\n`;
    tsContent += `  if (name.startsWith('inset-inline-end')) return inlineEnd;\n`;
    tsContent += `\n`;
    tsContent += `    const radius = (s1: string, s2: string) => {\n`;
    tsContent += `      const v = (s1 === 'top' || s1 === 'bottom') ? s1 : s2;\n`;
    tsContent += `      const h = (s1 === 'left' || s1 === 'right') ? s1 : s2;\n`;
    tsContent += `      return \`-\${v}-\${h}-radius\`;\n`;
    tsContent += `    };\n`;
    tsContent += `    const shape = (s1: string, s2: string) => {\n`;
    tsContent += `      const v = (s1 === 'top' || s1 === 'bottom') ? s1 : s2;\n`;
    tsContent += `      const h = (s1 === 'left' || s1 === 'right') ? s1 : s2;\n`;
    tsContent += `      return \`-\${v}-\${h}-shape\`;\n`;
    tsContent += `    };\n`;
    tsContent += `\n`;
    tsContent += `    const replacements = [\n`;
    tsContent += `      { logical: '-block-start', physical: \`-\${blockStart}\` },\n`;
    tsContent += `      { logical: '-block-end', physical: \`-\${blockEnd}\` },\n`;
    tsContent += `      { logical: '-inline-start', physical: \`-\${inlineStart}\` },\n`;
    tsContent += `      { logical: '-inline-end', physical: \`-\${inlineEnd}\` },\n`;
    tsContent += `      { logical: '-start-start-radius', physical: radius(blockStart, inlineStart) },\n`;
    tsContent += `      { logical: '-start-end-radius', physical: radius(blockStart, inlineEnd) },\n`;
    tsContent += `      { logical: '-end-start-radius', physical: radius(blockEnd, inlineStart) },\n`;
    tsContent += `      { logical: '-end-end-radius', physical: radius(blockEnd, inlineEnd) },\n`;
    tsContent += `      { logical: '-start-start-shape', physical: shape(blockStart, inlineStart) },\n`;
    tsContent += `      { logical: '-start-end-shape', physical: shape(blockStart, inlineEnd) },\n`;
    tsContent += `      { logical: '-end-start-shape', physical: shape(blockEnd, inlineStart) },\n`;
    tsContent += `      { logical: '-end-end-shape', physical: shape(blockEnd, inlineEnd) },\n`;
    tsContent += `      { logical: '-block', physical: \`-\${blockAxis}\` },\n`;
    tsContent += `      { logical: '-inline', physical: \`-\${inlineAxis}\` },\n`;
    tsContent += `    ];\n`;
    tsContent += `\n`;
    tsContent += `  let resolved = name;\n`;
    tsContent += `  for (const { logical, physical } of replacements) {\n`;
    tsContent += `    if (resolved.includes(logical)) {\n`;
    tsContent += `      resolved = resolved.replace(logical, physical);\n`;
    tsContent += `      break;\n`;
    tsContent += `    }\n`;
    tsContent += `  }\n`;
    tsContent += `\n`;
    tsContent += `  if (resolved === 'block-size') return writingMode.startsWith('vertical') ? 'width' : 'height';\n`;
    tsContent += `  if (resolved === 'inline-size') return writingMode.startsWith('vertical') ? 'height' : 'width';\n`;
    tsContent += `  if (resolved === 'min-block-size') return writingMode.startsWith('vertical') ? 'min-width' : 'min-height';\n`;
    tsContent += `  if (resolved === 'min-inline-size') return writingMode.startsWith('vertical') ? 'min-height' : 'min-width';\n`;
    tsContent += `  if (resolved === 'max-block-size') return writingMode.startsWith('vertical') ? 'max-width' : 'max-height';\n`;
    tsContent += `  if (resolved === 'max-inline-size') return writingMode.startsWith('vertical') ? 'max-height' : 'max-width';\n`;
    tsContent += `  if (resolved === 'contain-intrinsic-block-size') return writingMode.startsWith('vertical') ? 'contain-intrinsic-width' : 'contain-intrinsic-height';\n`;
    tsContent += `  if (resolved === 'contain-intrinsic-inline-size') return writingMode.startsWith('vertical') ? 'contain-intrinsic-height' : 'contain-intrinsic-width';\n`;
    tsContent += `\n`;
    tsContent += `  return resolved;\n`;
    tsContent += `}\n`;
    tsContent += `\n`;
    tsContent += `export function resolvePhysicalProperty(name: string, writingMode: string = 'horizontal-tb', direction: string = 'ltr'): string {\n`;
    tsContent += `  for (const logical in LOGICAL_MAPPING) {\n`;
    tsContent += `    const resolved = resolveLogicalProperty(logical, writingMode, direction);\n`;
    tsContent += `    if (resolved === name) {\n`;
    tsContent += `      return logical;\n`;
    tsContent += `    }\n`;
    tsContent += `  }\n`;
    tsContent += `  return name;\n`;
    tsContent += `}\n`;
    tsContent += `\n`;
    tsContent += `export function getPhysicalToLogicalMapping(physicals: readonly string[], writingMode: string = 'horizontal-tb', direction: string = 'ltr'): Record<string, string> {\n`;
    tsContent += `  const mapping: Record<string, string> = {};\n`;
    tsContent += `  for (const ph of physicals) {\n`;
    tsContent += `    mapping[ph] = resolvePhysicalProperty(ph, writingMode, direction);\n`;
    tsContent += `  }\n`;
    tsContent += `  return mapping;\n`;
    tsContent += `}\n`;
    
    fs.writeFileSync(LOGICAL_MAPPING_TS_PATH, tsContent);
    console.log(`Updated ${LOGICAL_MAPPING_TS_PATH} with ${Object.keys(mappings).length} mappings.`);
}

main();
