/** @license Copyright 2026 Google LLC. SPDX-License-Identifier: Apache-2.0 */
import fs from 'node:fs';
import path from 'node:path';

const SPEC_PATH = 'submodules/csswg-drafts/css-color-4/Overview.bs';
const OUTPUT_PATH = 'src/data/gen/colors.ts';

function main() {
  const absoluteSpecPath = path.resolve(SPEC_PATH);
  console.log(`Parsing color list from local spec: ${absoluteSpecPath}...`);
  
  if (!fs.existsSync(absoluteSpecPath)) {
    console.error(`Error: Spec file not found at ${absoluteSpecPath}`);
    process.exit(1);
  }

  const content = fs.readFileSync(absoluteSpecPath, 'utf8');
  
  // Find the named-color-table block
  const tableStartIndex = content.indexOf('<table class="named-color-table"');
  if (tableStartIndex === -1) {
    throw new Error('Could not find class="named-color-table" in spec');
  }
  const tableEndIndex = content.indexOf('</table>', tableStartIndex);
  if (tableEndIndex === -1) {
    throw new Error('Could not find closing </table> tag in spec');
  }
  
  const tableContent = content.slice(tableStartIndex, tableEndIndex);
  
  const rgbColors: Record<string, [number, number, number, number?]> = {
    transparent: [0, 0, 0, 0]
  };

  // Match lines like:
  // <td style="background:aliceblue">&nbsp;<td style="background:#f0f8ff">&nbsp;<th scope=row><dfn>aliceblue</dfn><td>#f0f8ff<td>240 248 255
  const regex = /<dfn>([a-zA-Z0-9_-]+)<\/dfn><td>(#[0-9a-fA-F]+)<td>(\d+)\s+(\d+)\s+(\d+)/g;
  let match;
  let count = 0;
  
  while ((match = regex.exec(tableContent)) !== null) {
    const name = match[1].toLowerCase();
    const r = parseInt(match[3], 10);
    const g = parseInt(match[4], 10);
    const b = parseInt(match[5], 10);
    rgbColors[name] = [r, g, b];
    count++;
  }

  if (count === 0) {
    throw new Error('Parsed 0 colors from table, regex might be outdated');
  }

  // Sort keys alphabetically
  const sortedColors = Object.keys(rgbColors)
    .sort()
    .reduce((acc, key) => {
      acc[key] = rgbColors[key];
      return acc;
    }, {} as Record<string, [number, number, number, number?]>);

  let fileContent = `/**
 * @license
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */\n\n`;
  fileContent += `// @generated by scripts/codegen/generate_colors.ts. Do not edit.\n// Machine-generated.\n\n`;

  let colorsStr = '{\n';
  for (const [name, value] of Object.entries(sortedColors)) {
    colorsStr += `  "${name}": [${value.join(', ')}],\n`;
  }
  colorsStr += '}';

  fileContent += `export const NAMED_COLORS: Record<string, [number, number, number, number?]> = ${colorsStr};\n`;

  fs.writeFileSync(OUTPUT_PATH, fileContent, 'utf8');
  console.log(`Generated ${OUTPUT_PATH} with ${Object.keys(sortedColors).length} color mappings (parsed ${count} from spec).`);
}

main();
