/**
 * @license
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import fs from 'node:fs';

const WEBREF_CSS_PATH = 'node_modules/@webref/css/css.json';
const SHORTHANDS_DATA_TS_PATH = 'src/data/shorthands.ts';

function main() {
    const css = JSON.parse(fs.readFileSync(WEBREF_CSS_PATH, 'utf8'));
    const allShorthands: Record<string, string[]> = {};


    for (const p of css.properties) {
        if (p.longhands) {
            allShorthands[p.name] = p.longhands;
        }
    }

    let data = `// @generated by scripts/codegen/generate_shorthands.ts. Do not edit.\n// Machine-generated shorthand data.\n\n`;
    data += `export const SHORTHANDS_DATA = {\n`;
    for (const name of Object.keys(allShorthands).sort()) {
        data += `  '${name}': ${JSON.stringify(allShorthands[name])},\n`;
    }
    data += `} as const;\n`;

    fs.writeFileSync(SHORTHANDS_DATA_TS_PATH, data);
    console.log(`Generated ${SHORTHANDS_DATA_TS_PATH} with ${Object.keys(allShorthands).length} shorthands.`);
}

main();
